# 网站域名,必选
base_url = "https://12101111.github.io"

# 标题,用于RSS而不是网页
title = "12101111's blog"

# 介绍,用于RSS而不是网页
description = ""

default_language = "cn"

# 主题名
theme = "even"

# 生成RSS文件
generate_feed = true

feed_filename = "rss.xml"

# 是否编译 sass
compile_sass = true

# 生成搜索索引,支持搜索与否取决于主题
build_search_index = false

# 检查外部死链,极其耗时
check_external_links = false

# taxonomies是页面的分类方式,这些变量先在这里定义,随后会根据模板生成对应的分类页面
# 模板在theme或者templates下的name文件夹,需要
# `list.html`(分类列表)和`single.html`(每个分类下的文章列表)
# 定义格式:{name: "名称",paginate_by: 5, rss: 是否生成RSS}
# paginate_by:文章列表一个页面的文章数量(可选,0为不分页)
# 建议如下
taxonomies = [
    {name = "tags"},
    {name = "categories"},
]

# 不对content文件夹中满足以下通配符的文件进行处理和渲染
ignored_content = ["*.{tmp,xlsx}", "*draft.md"]

[markdown]

# 使用代码高亮
highlight_code = true

# 代码高亮主题,列表见上面的官方文档
highlight_theme = "solarized-light"

# extra存放没有被程序定义的变量,可以被模板和主题使用
[extra]
even_title = "Coding..."

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    #{url = "$BASE_URL/about", name = "About"},
]
